apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver
  labels:
    app: contactfi
spec:
  replicas: 2
  selector:
    matchLabels:
      app: contactfi
  template:
    metadata:
      labels:
        app: contactfi
    spec:
      containers:
      - name: contactfi
        image: mandovg/contactfi:1.1
        ports:
        - containerPort: 3000